name: Build APK

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Download and install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        mkdir -p $HOME/.android/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/.android/cmdline-tools
        
        # List the unzipped contents for debugging
        echo "Directory structure after unzip:"
        ls -R $HOME/.android/cmdline-tools
        
        # Adjust based on actual structure
        if [ -d "$HOME/.android/cmdline-tools/cmdline-tools" ]; then
          mv $HOME/.android/cmdline-tools/cmdline-tools $HOME/.android/cmdline-tools/tools
        else
          mv $HOME/.android/cmdline-tools/* $HOME/.android/cmdline-tools/tools
        fi
        
        yes | $HOME/.android/cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/.android "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Set up environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/.android" >> $GITHUB_ENV
        echo "ANDROID_HOME=$HOME/.android" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/.android/cmdline-tools/tools/bin" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/.android/platform-tools" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/.android/build-tools/30.0.3" >> $GITHUB_ENV

    - name: Build APK with Buildozer
      run: buildozer android debug
