name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk-headless
        sudo apt-get install -y unzip

    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        mkdir -p $HOME/.android/cmdline-tools
        unzip -d $HOME/.android/cmdline-tools commandlinetools-linux-7583922_latest.zip
        echo 'export ANDROID_HOME=$HOME/.android/cmdline-tools' >> $HOME/.bashrc
        echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools' >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Install buildozer
      run: pip install buildozer

    - name: Build APK
      run: buildozer android debug
