name: Build APK

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Build APK with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: android debug
        workdir: .  # Directory where buildozer.spec is located
