name: Build Kivy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      uses: android/setup-android@v2
      with:
        sdk-platform: '30'
        ndk-version: '21.4.7075529'

    - name: Install Android Build Tools
      run: sdkmanager "build-tools;30.0.3" --sdk_root=$ANDROID_SDK_ROOT

    - name: Install Buildozer
      run: |
        pip install --upgrade buildozer
        pip install cython

    - name: Build APK
      run: buildozer android debug

# Buildozer spec configuration...
