name: Build Kivy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install required system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk unzip zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
        libbz2-dev libreadline-dev libsqlite3-dev llvm libncursesw5-dev xz-utils tk-dev libxml2-dev \
        libxmlsec1-dev liblzma-dev lzma libtool pkg-config autoconf automake

    - name: Set up Buildozer
      run: |
        pip install --upgrade buildozer
        pip install cython

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: 'commandlinetools-latest'
        ndk-version: '21.4.7075529'

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Install Android SDK components
      run: |
        sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

    - name: Build APK
      run: buildozer android debug
