name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(/bin/date -u '+%Y%m%d')"

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Install required system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
                                  libbz2-dev libreadline-dev libsqlite3-dev llvm libncursesw5-dev xz-utils \
                                  tk-dev libxml2-dev libxmlsec1-dev liblzma-dev lzma libtool pkg-config \
                                  autoconf automake

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade Cython==0.29.32 virtualenv

      - name: Setup virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer

      - name: Build with Buildozer
        run: |
          source venv/bin/activate
          buildozer android debug --verbose
        continue-on-error: true

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: .buildozer/android/platform/build-armeabi-v7a/build/build.log

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
          
