name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          libssl-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev
        pip install buildozer

    - name: Build APK
      env:
        ANDROID_SDK_ROOT: ${{ secrets.ANDROID_SDK_ROOT }}
        ANDROID_BUILD_TOOLS_PATH: ${{ secrets.ANDROID_BUILD_TOOLS_PATH }}
        ANDROID_SDK_TOOLS_PATH: ${{ secrets.ANDROID_SDK_TOOLS_PATH }}
      run: |
        buildozer -v android debug
