name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: sudo apt-get install -y git

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-global-

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install required system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip zlib1g-dev libncurses5-dev libffi-dev libssl-dev \
                                  libbz2-dev libreadline-dev libsqlite3-dev llvm libncursesw5-dev xz-utils \
                                  tk-dev libxml2-dev libxmlsec1-dev liblzma-dev lzma libtool pkg-config \
                                  autoconf automake

      - name: Install Android SDK
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk
          curl -o sdk-tools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          sudo unzip -qq sdk-tools-linux.zip -d /usr/local/lib/android/sdk/cmdline-tools
          sudo mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo chown -R $USER:$USER /usr/local/lib/android/sdk
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Check Android SDK Installation
        run: |
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          sdkmanager --list

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install --upgrade Cython==0.29.32 virtualenv

      - name: Setup virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer

      - name: Build with Buildozer
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          PATH: $PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        run: |
          source venv/bin/activate
          buildozer android debug --verbose

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: .buildozer/android/platform/build-armeabi-v7a/build/build.log

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
