name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git

      - name: Install Python and required packages
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Cython
        run: |
          python -m pip install Cython

      - name: Install Buildozer
        run: |
          python -m pip install buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
