name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git python3-dev python3-pip build-essential
        sudo apt-get install -y libffi-dev libssl-dev liblzma-dev zlib1g-dev
        sudo apt-get install -y cython
        sudo apt-get install -y openjdk-8-jdk
        pip install --upgrade pip virtualenv
        pip install buildozer

    - name: Install Cython
      run: pip install Cython

    - name: Install Aidl
      run: sudo apt-get install -y aidl

    - name: Build APK
      run: |
        virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt
        buildozer android debug
