name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java 8
      uses: actions/setup-java@v2
      with:
        java-version: 8

    - name: Install buildozer and dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-venv libffi-dev ccache libssl-dev
        pip install --upgrade cython==0.29.19 virtualenv
        pip install buildozer

    - name: Install Android SDK and NDK
      run: |
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        mkdir -p $HOME/android-sdk
        unzip -qq sdk-tools-linux-4333796.zip -d $HOME/android-sdk
        echo "sdk.dir=$HOME/android-sdk" >> $GITHUB_WORKSPACE/local.properties
        yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses
        $HOME/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.2" "ndk-bundle"

    - name: Build the APK
      run: |
        buildozer android debug
      env:
        ANDROIDSDK: ${{ secrets.ANDROIDSDK }}
        ANDROIDNDK: ${{ secrets.ANDROIDNDK }}

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: bin/*.apk
