name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d cmdline-tools
          mkdir -p $ANDROID_HOME/cmdline-tools/
          mv cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

      - name: Accept Android licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Aidl
        run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;31.0.0" "platforms;android-31"

      - name: Check Aidl installation
        run: $ANDROID_HOME/cmdline-tools/latest/bin/aidl --version

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer

      - name: Build APK with Buildozer
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: bin/*.apk
