name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup virtual environment and install buildozer
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer
          apt-get update
          apt-get install -y git
        shell: bash

      - name: Build with Buildozer
        run: |
          source venv/bin/activate
          buildozer android debug --verbose
        continue-on-error: true

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: bin/*.apk

      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: .buildozer/android/platform/build-armeabi-v7a/build/build.log
