name: Build Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git openjdk-8-jdk zlib1g-dev libncurses5-dev libgdbm-dev libc6-dev libbz2-dev libsqlite3-dev libreadline-dev libssl-dev liblzma-dev tk-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build the APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyApp-APK
        path: bin/*.apk
