name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libsdl2-dev \
            libssl-dev \
            libjpeg-dev \
            libtiff-dev \
            libffi-dev \
            libglu1-mesa-dev \
            libgstreamer-plugins-base1.0-dev \
            libxmu-dev \
            libopus0 \
            opus-tools \
            portaudio19-dev \
            python3-dev \
            zlib1g-dev
          pip install buildozer

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "build-tools;31.0.0" "platforms;android-31"

      - name: Set up Android SDK environment
        run: |
          echo "export ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer -v android debug
